### ISSUE TITLE
 Practica de Conjuntos, subconjuntos y producto

### ISSUE THREAD

**Issue by UrielGB10** [SistemasTecTlaxiaco/practica-de-conjuntos-equipo-de-uriel-edwin-araceli-1as#1]
[Practica.de.Conjuntos.mate.discreta.pdf](https://github.com/SistemasTecTlaxiaco/practica-de-conjuntos-equipo-de-uriel-edwin-araceli-1as/files/7348192/Practica.de.Conjuntos.mate.discreta.pdf)

**Comment by 7177981** [comment]
el trabajo contiene descripciones y resultados de los ejercicios pero la conclusión no cuenta con lo pedido en la rubrica
CALIFICACIÓN = 17%

**Comment by josealfredo79** [comment]
Bien hecho y revisado
